#!/bin/sh
# chkconfig: 2345 32 70
# Description: Activates/Deactivates JH Scheduler

export JHLAVA_TOP=__LAVATOP__
. ${JHLAVA_TOP}/conf/profile.jhlava

# kill the old daemons first.
#
kill_daemons()
{
#    killall -q lim res sbatchd  mbatchd
	apid=`ps -ef | grep $LSF_SERVERDIR | awk '{if($8!="grep" && $8!="bash" && $8!="sh") print $2}'`
	#echo $apid
	if [ "x$apid" != "x" ]; then
		kill $apid > /dev/null 2>&1
		sleep 1
	fi
}

getpid()
{
	_pid=`ps -ef | grep $1 | awk '{if($8!="grep" && $8!="bash" && $8!="sh") print $2}'`
	echo $_pid
	_pid= 
}

opcode="$1"
if [ "$opcode" = "restart" ]
then 
   opcode="start"
   echo "Stopping daemons..."
   kill_daemons
fi

LSF_CONF=$JHLAVA_TOP/conf/lsf.conf
# Process the requested operation.
case "$opcode" in
  'stop')
        echo "Stopping daemons..."
        kill_daemons
        exit 0
        ;;

  'start')

#        kill_daemons
        echo "Starting daemons..."

	ID=`id -u`
        if [ "$ID" != 0 ]; then
           # single user mode use this
           # to run test clusters
	   $LSF_SERVERDIR/lim -1
           echo "lim -1 started"
	   $LSF_SERVERDIR/res -1
           echo "res -1 started"
	   $LSF_SERVERDIR/sbatchd -1
           echo "sbatchd -1 started"
        else
           # multi user mode
	   $LSF_SERVERDIR/lim
           echo "lim started"
	   $LSF_SERVERDIR/res
           echo "res started"
	   $LSF_SERVERDIR/sbatchd
           echo "sbatchd started"
        fi
        exit 0
        ;;
  'status')
        PID=$(getpid ${LSF_SERVERDIR}/lim)
        echo "lim pid: <$PID>"
        PID=$(getpid ${LSF_SERVERDIR}/res)
        echo "res pid: <$PID>"
        PID=$(getpid ${LSF_SERVERDIR}/sbatchd)
        echo "sbatchd pid: <$PID>"
        PID=$(getpid ${LSF_SERVERDIR}/mbatchd)
        echo "lim mbatchd: <$PID>"
        exit 0
        ;;
  *)
        echo "Script for starting up and shutting down jhlava"
        echo "Usage: $0 { start | stop | status | restart }"
        exit 0
        ;;
esac
